# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pipeboard < Formula
  desc "CLI for managing Meta, Google, and TikTok Ads via Pipeboard"
  homepage "https://github.com/pipeboard-co/pipeboard-cli"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pipeboard-co/pipeboard-cli/releases/download/v0.1.0/pipeboard_darwin_amd64.tar.gz"
      sha256 "16958ac3554dcc1c7bbfe45ca14e03d0e63039437a46ca827e6cb5ad52d7a0a5"

      define_method(:install) do
        bin.install "pipeboard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pipeboard-co/pipeboard-cli/releases/download/v0.1.0/pipeboard_darwin_arm64.tar.gz"
      sha256 "163ce6d4fdc2606048cf4d667853d809ad291ee6a15fd0a2f0ab67835ecc99c7"

      define_method(:install) do
        bin.install "pipeboard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pipeboard-co/pipeboard-cli/releases/download/v0.1.0/pipeboard_linux_amd64.tar.gz"
      sha256 "2fc1d61bc556a2cf330af9fe27607f44e4ee0220efaefecf40b44be4bef0464a"
      define_method(:install) do
        bin.install "pipeboard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pipeboard-co/pipeboard-cli/releases/download/v0.1.0/pipeboard_linux_arm64.tar.gz"
      sha256 "26e400caf09e4543b3b2302da428574cec41a06048ceda893b7d233b19b899db"
      define_method(:install) do
        bin.install "pipeboard"
      end
    end
  end
end
