# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PipeboardCli < Formula
  desc "CLI for managing Meta, Google, and TikTok Ads via Pipeboard"
  homepage "https://github.com/pipeboard-co/pipeboard-cli"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pipeboard-co/pipeboard-cli/releases/download/v0.1.0/pipeboard-cli_darwin_amd64.tar.gz"
      sha256 "f0e8e49ae9776f538a08151288bcb082131882e40276158598c95a42e0d40d5b"

      define_method(:install) do
        bin.install "pipeboard-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pipeboard-co/pipeboard-cli/releases/download/v0.1.0/pipeboard-cli_darwin_arm64.tar.gz"
      sha256 "d0d1ef876f99251f55ba50778f35767578656b7e2f702e32b6d00c0c5a178432"

      define_method(:install) do
        bin.install "pipeboard-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pipeboard-co/pipeboard-cli/releases/download/v0.1.0/pipeboard-cli_linux_amd64.tar.gz"
      sha256 "b064dd4b81e2a5c51ede7ca641cb66741fadef78789c7672cbcca3df91f98425"
      define_method(:install) do
        bin.install "pipeboard-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pipeboard-co/pipeboard-cli/releases/download/v0.1.0/pipeboard-cli_linux_arm64.tar.gz"
      sha256 "e0d8162b940d810c1082a41b17d4c6791095f9397d47fea5f7ed1b123a5a4074"
      define_method(:install) do
        bin.install "pipeboard-cli"
      end
    end
  end
end
